### PR TITLE
Newest German translations ready

### PR DESCRIPTION
**Pull request by Namnodorel**
The title says everything ;)

### CODE REVIEW

**Comment by Co0sh** [comment]
I added a few texts (errors) and I'm going to add more (compass targets), so let's wait a bit with merging translations, alright? ^^

**Comment by Namnodorel** [comment]
Fine :)

**Comment by Co0sh** [comment]
Done :smile:

**Comment by Namnodorel** [comment]
Done, too :)

**Comment by Co0sh** [comment]
Thanks ^^

**Pull request merged**
