### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by Namnodorel**
This pull request just fixes some of the translations where I thought there would be better words and adds a few new ones. It does not finish the German translation, maybe I'm gonna do that in the future.

### CODE REVIEW

**Comment by Co0sh** [comment]
Wrong encoding - it's UTF-8 and needs to be ANSI. You can change that i.e. in Notepad++'s "Encoding" menu.

Also, how about the rest of the texts? Pretty please :smiley:

**Comment by Namnodorel** [comment]
Uuum... Don't even have Notepad, I use Atom ;) Will ISO-8859-1 do the job? It does work, too, and Atom doesn't have ANSI support...

**Comment by Co0sh** [comment]
Yes, Java uses ISO 8859-1, so it will work too.

**Comment by Namnodorel** [comment]
Okay, fixed and added ^^ Apparently I didn't even need to create a new pull request (I'm fairly new to contribution by pull requests)

**Comment by Co0sh** [comment]
Almost ready to merge :smile: Only one line is missing: `points-to=Zeigt auf` - it's displayed when no option is selected and the view is inactive. I also think `points-to-player=zeigt auf Spieler Optionen` should start with upper case letter, shouldn't it?

**Comment by Namnodorel** [comment]
Yes, it should - but you confuse me a little bit: "Zeigt auf" means "points to" like in "This reference points to this location". What you said doesn't seem similar. Is it still correct?

**Comment by Co0sh** [comment]
That's exactly what it should mean. I don't know German, but in English it's like this:

* NPC option is displayed, the text says `Points to player options:`
* Player option is displayed, the text says `Points to NPC options:`
* Nothing is displayed (i.e. because there are no conversations), the text says `Points to`

I assumed it would be `Zeigt auf`.

**Comment by Namnodorel** [comment]
Okay, everything should be fine now :) With this one I was especially unsure, because the previous translation was similar to "Give points to...". Or at least you could've confused it.

**Comment by Co0sh** [comment]
I was talking about that one:

editor

It's `points-to=` in _lang.properties_ and it's missing in your translation. I'm sorry for bothering you with all these commits, but it would be ugly if every string was translated and only one was displayed in English, right? ^^

**Comment by Namnodorel** [comment]
Yes it would ^^ Although that string _should_ also be translated... I have it in my local file, and GitKraken is not showing me any differences from the repo...

**Comment by Co0sh** [comment]
Yes, you're right. I must have missed it when I was looking for that one missing string. Look, there are [121 lines](https://github.com/Namnodorel/BetonQuest-Editor/blob/master/src/pl/betoncraft/betonquest/editor/resource/lang/lang_de.properties#L121) here and [122 lines](https://github.com/Namnodorel/BetonQuest-Editor/blob/master/src/pl/betoncraft/betonquest/editor/resource/lang/lang.properties#L122) there.

**Comment by Co0sh** [comment]
Wait, my bad. There are two `about` strings in the original translation - one for the menu bar and one for about window title. I'll fix this in a minute.

**Comment by Co0sh** [comment]
Alright, there should be an additional `about-title` string which says in English "About BetonQuest Editor".

**Comment by Co0sh** [comment]
Thanks ^^ :+1: :beer:

**Pull request merged**
